# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khgORemI1i2xZ_0Xraqxvdn7A5JnBInk
"""

first_name = 'Krati'
last_name = 'Shrivastav'
country = 'India'
city = 'Bengaluru'
age = 1
is_married = False
skills = ['Python','HTML','CSS','Java']
person_info = {'first_name':'Krati','last_name':'Shrivastav','county':'India','age':'1'}

print('First Name is :',first_name)
print('last Name is:',last_name)
print('Length of first name',len(first_name))
print('Length of last name',len(last_name))
print('My city is:',city)
print('My country is:',country)
print('Married or not',is_married)
print('My skills is:',skills)
print('the person:',person_info)

first_name,last_name,city,country = 'Krati','Shrivastav','Bangalore','India'

print(first_name)
print(last_name)
print(city)
print(country)

print('Addition',1+2)
print('Multiplication',3*2)
print('Substraction',4/2)
print('Modulus:',3%2)
print('Division without remainder',3//2)
print('Exponential:',3**2)

print('Floating number',3.14)
print('Multiplying complex numbers:',(1+1j)*(1-1j))

a = 3
b = 2
print("Addition",a + b)
print("Multipy",a * b)
print("Substraction",a - b)
print("Module",a % b)
print("division",a / b)
print("Division  without remainder",a // b)

num_one = 3
num_two = 4
total = num_one + num_two
diff = num_one - num_two
product = num_one * num_two
div = num_one / num_two
remainder = num_two % num_one

print(total)
print(diff)
print(product)
print(div)
print(remainder)

#Calculating area of rectangle
radius = 12
area_of_circle = 3.14*radius**2
print(area_of_circle)

#Calculating area of rectangle
length = 10
width = 12
area_of_rectangle = length * width
print(area_of_rectangle)

#Calculating weight of object
mass = 75
gravity = 9.81
weight = mass * gravity
print(weight)

a = 3
b = 2
print(a > b)
print(a >= b)
print(a < b)
print(a < a)
print(a == a)
print(a!=a)
print(b == b)
print(b > a)
print(b!=b)
print(len('mango')==len('avocado'))
print(len('mango')!=len('avocado'))
print(len('milk')< len('avocade'))
print(len('milk')>len('avocado'))

print('True == True:',True == True)
print('True == False:',True == False)
print("False == False:",False == False)
print('True and True:',True and True)
print('True or False:',True or Flase)

print(1 is 1)
print(1 is not 2)
print('A' in 'Ankita')
print('B' in 'shwetabh')
print('coding' in 'coding for all')
print('a' in 'an')
print(4 is 2**2)

print(3>2 and 4 > 3)
print(3 < 2 and 4 < 3)
print(3 > 2 and 4 > 3)
print(3>2 or 4 < 3)
print(3<2 or 4>3)
print(not 3 > 2)
print(not True)
print(not not True)
print(not not False)
