# -*- coding: utf-8 -*-
"""LIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8G1SHFNZMWMJgnvMOvxsDIEPi91i-wp

#Data Structure-----LIST
"""

l = []
l

type(l)

len(l)

l.append(10)
l

l.append(20)
l

id(l)

l.append(30)
l.append(40)
l.append(50)
l

len(l)

l1 = l.copy()
l1

l1.append(100)
l1

l == l1

print(l)
print(l1)

l != l1

print(len(l))
print(len(l1))

id(l1)

l1.clear()
l1

l.append('nit')
l.append(2.3)
l.append(1+2j)
l.append(True)
l.append([1,2,3,4,5])
l
