{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "198f22d9-30c8-4a51-98fd-71258435aa57",
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n",
    "import streamlit as st\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "sns.set(style='whitegrid')\n",
    "tips = sns.load_dataset('tips')\n",
    "st.title(\"Comprehensive Tips Dataset Visualizations\")\n",
    "st.write(\"This app displays a variety of Seaborn plots exploring the Tips dataset, which includes data on restaurant bills and tips.\")\n",
    "def display_plot(title,plot_func):\n",
    "    st.subheader(title)\n",
    "    fig,ax=plt.subplots(figsize=(8,6))\n",
    "    plot_func(ax)\n",
    "    st.pyplot(fig)\n",
    "    plt.close(fig)\n",
    "\n",
    "def scatter_plot(ax):\n",
    "    sns.scatterplot(data=tips, x=\"total_bill\", y=\"tip\", hue=\"time\", size=\"size\", palette=\"deep\", ax=ax)\n",
    "    ax.set_title(\"Scatter Plot: Total Bill vs Tip by Time and Size\")\n",
    "def line_plot(ax):\n",
    "    sns.lineplot(data=tips, x=\"size\", y=\"total_bill\", hue=\"sex\", ci=None, marker=\"o\", ax=ax)\n",
    "    ax.set_title(\"Line Plot: Total Bill by Party Size and Sex\")\n",
    "\n",
    "def bar_plot(ax):\n",
    "    sns.barplot(data=tips, x=\"day\", y=\"total_bill\", hue=\"sex\", palette=\"muted\", ax=ax)\n",
    "    ax.set_title(\"Bar Plot: Average Total Bill by Day and Sex\")\n",
    "\n",
    "def box_plot(ax):\n",
    "    sns.boxplot(data=tips, x=\"day\", y=\"tip\", hue=\"smoker\", palette=\"Set2\", ax=ax)\n",
    "    ax.set_title(\"Box Plot: Tips by Day and Smoker Status\")\n",
    "\n",
    "def violin_plot(ax):\n",
    "    sns.violinplot(data=tips, x=\"day\", y=\"total_bill\", hue=\"time\", split=True, palette=\"pastel\", ax=ax)\n",
    "    ax.set_title(\"Violin Plot: Total Bill by Day and Time\")    \n",
    "\n",
    "def count_plot(ax):\n",
    "    sns.countplot(data=tips, x=\"day\", hue=\"smoker\", palette=\"dark\", ax=ax)\n",
    "    ax.set_title(\"Count Plot: Orders by Day and Smoker Status\")\n",
    "\n",
    "def reg_plot(ax):\n",
    "    sns.regplot(data=tips, x=\"total_bill\", y=\"tip\", scatter_kws={\"s\": 50}, line_kws={\"color\": \"red\"}, ax=ax)\n",
    "    ax.set_title(\"Regression Plot: Total Bill vs Tip\")\n",
    "\n",
    "def hist_plot(ax):\n",
    "    sns.histplot(data=tips, x=\"total_bill\", kde=True, bins=20, color=\"blue\", ax=ax)\n",
    "    ax.set_title(\"Histogram: Distribution of Total Bill\")\n",
    "\n",
    "def strip_plot(ax):\n",
    "    sns.stripplot(data=tips, x=\"day\", y=\"tip\", hue=\"sex\", palette=\"Set1\", jitter=True, ax=ax)\n",
    "    ax.set_title(\"Strip Plot: Tips by Day and Sex\")\n",
    "\n",
    "def swarm_plot(ax):\n",
    "    sns.swarmplot(data=tips, x=\"day\", y=\"tip\", hue=\"smoker\", palette=\"Set3\", ax=ax)\n",
    "    ax.set_title(\"Swarm Plot: Tips by Day and Smoker Status\")\n",
    "\n",
    "def kde_plot(ax):\n",
    "    sns.kdeplot(data=tips, x=\"total_bill\", hue=\"sex\", fill=True, palette=\"tab10\", ax=ax)\n",
    "    ax.set_title(\"KDE Plot: Total Bill Density by Sex\")\n",
    "\n",
    "st.subheader(\"Pair Plot: Numerical Variables by Sex\")\n",
    "pair_fig = sns.pairplot(tips, hue=\"sex\", vars=[\"total_bill\", \"tip\", \"size\"], palette=\"husl\")\n",
    "pair_fig.fig.suptitle(\"Pair Plot: Numerical Variables by Sex\", y=1.02)\n",
    "st.pyplot(pair_fig.fig)\n",
    "plt.close(pair_fig.fig)\n",
    "\n",
    "st.subheader(\"Joint Plot: Total Bill vs Tip by Smoker\")\n",
    "joint_fig = sns.jointplot(data=tips, x=\"total_bill\", y=\"tip\", kind=\"scatter\", hue=\"smoker\", palette=\"coolwarm\")\n",
    "joint_fig.fig.suptitle(\"Joint Plot: Total Bill vs Tip by Smoker\", y=1.02)\n",
    "st.pyplot(joint_fig.fig)\n",
    "plt.close(joint_fig.fig)\n",
    "\n",
    "st.subheader(\"FacetGrid: Total Bill by Time and Smoker\")\n",
    "g = sns.FacetGrid(tips, col=\"time\", row=\"smoker\", margin_titles=True)\n",
    "g.map(sns.histplot, \"total_bill\", bins=15)\n",
    "g.fig.suptitle(\"FacetGrid: Total Bill by Time and Smoker\", y=1.02)\n",
    "st.pyplot(g.fig)\n",
    "plt.close(g.fig)\n",
    "\n",
    "st.subheader(\"Catplot (Point): Tips by Day and Sex\")\n",
    "cat_fig = sns.catplot(data=tips, x=\"day\", y=\"tip\", hue=\"sex\", kind=\"point\", palette=\"bright\")\n",
    "cat_fig.fig.suptitle(\"Catplot (Point): Tips by Day and Sex\", y=1.02)\n",
    "st.pyplot(cat_fig.fig)\n",
    "plt.close(cat_fig.fig)\n",
    "\n",
    "display_plot(\"Scatter Plot\", scatter_plot)\n",
    "display_plot(\"Line Plot\", line_plot)\n",
    "display_plot(\"Bar Plot\", bar_plot)\n",
    "display_plot(\"Box Plot\", box_plot)\n",
    "display_plot(\"Violin Plot\", violin_plot)\n",
    "display_plot(\"Count Plot\", count_plot)\n",
    "display_plot(\"Regression Plot\", reg_plot)\n",
    "display_plot(\"Histogram\", hist_plot)\n",
    "display_plot(\"Strip Plot\", strip_plot)\n",
    "display_plot(\"Swarm Plot\", swarm_plot)\n",
    "display_plot(\"KDE Plot\", kde_plot)\n",
    "\n",
    "st.write(\"All Seaborn plots for the Tips dataset have been generated!\")\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
